### ISSUE TITLE
[Question] Include package reference not working with dotnet pack

### ISSUE THREAD

**Issue by kYann** [kzu/til#1]
Hello,

Thanks for this great content.
I've used the target described here to add package ref in my package output :
https://github.com/kzu/til/blob/master/msbuild/how-to-include-package-reference-files-in-your-nuget-package.md

It works great when building the project, but not with the dotnet pack command.

I've tried to debug it, but my msbuild skills are pretty limited. If you could give me a hint it would help me a lot.

Thanks,

**Comment by kzu** [comment]
What might be happening is that the `dotnet pack` command doesn't run the `ResolvePackageAsset` at all. If so, you can add a `BeforeTargets=Path` to see if that fixes it. If it does, plz do let me know and I'll update the doc 👍.

Thanks for reporting this! (also, I use NuGetizer, which is why I haven't noticed the issue)

**Comment by kzu** [comment]
Hey, here's a sample that works:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Scriban" Version="2.1.2" PrivateAssets="all" Pack="true" />
  </ItemGroup>

  <!-- For every PackageReference with Pack=true, we include the assemblies from it in the package -->
  <Target Name="AddPackDependencies" 
          Inputs="@(RuntimeCopyLocalItems)" 
          Outputs="%(RuntimeCopyLocalItems.NuGetPackageId)" 
          DependsOnTargets="ResolvePackageAssets"
          AfterTargets="ResolvePackageAssets">
    <ItemGroup>
      <NuGetPackageId Include="@(RuntimeCopyLocalItems -> '%(NuGetPackageId)')" />
    </ItemGroup>
    <PropertyGroup>
      <NuGetPackageId>@(NuGetPackageId -&gt; Distinct())</NuGetPackageId>
    </PropertyGroup>
    <ItemGroup>
      <PackageReferenceDependency Include="@(PackageReference -&gt; WithMetadataValue('Identity', '$(NuGetPackageId)'))" />
    </ItemGroup>
    <PropertyGroup>
      <NuGetPackagePack>@(PackageReferenceDependency -> '%(Pack)')</NuGetPackagePack>
    </PropertyGroup>
    <ItemGroup Condition="'$(NuGetPackagePack)' == 'true'">
      <_PackageFiles Include="@(RuntimeCopyLocalItems)" PackagePath="$(BuildOutputTargetFolder)/$(TargetFramework)/%(Filename)%(Extension)" />
      <RuntimeCopyLocalItems Update="@(RuntimeCopyLocalItems)" CopyLocal="true" Private="true" />
      <ResolvedFileToPublish Include="@(RuntimeCopyLocalItems)" CopyToPublishDirectory="PreserveNewest" RelativePath="%(Filename)%(Extension)" />
    </ItemGroup>
  </Target>

</Project>
```

run `dotnet pack` and I get exactly what's shown in the article:

![image](https://user-images.githubusercontent.com/169707/101426773-6138b900-38dc-11eb-98a2-1bb17e648653.png)

Maybe there's something else going on? Would you care to attach a binlog?

**Comment by kYann** [comment]
Thanks so muck for taking the time to look at this.

The issue is that I was using the `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>` property. And when this property is set the dotnet pack command does not create the package with Scriban included.

I've just removed this property and ti works.

**Comment by kzu** [comment]
Uu, that's unexpected! Let me dig deeper on that scenario then 👍

**Comment by kzu** [comment]
Ok, that's weird. I run `dotnet build` with that added property, on my sample project from above, and it worked and packed the Scriban dependency. I'd love it if you could run with `-bl` and attach the binlog to take a look. I definitely can't repro.

Also, I have .NET 5 and MSBuild 16.8 installed, so maybe that's a bug that was fixed since?

**Comment by kYann** [comment]
I have .Net 5 and last visual studio install. But the command that I use is `dotnet pack` not `dotnet build`.

I had set GeneratePackageOnBuild property to create a package on my laptop at each build. But on the CI server I use dotnet pack.

I've attached the output of the binlog.
[msbuild.zip](https://github.com/kzu/til/files/5674957/msbuild.zip)

Thanks again for taking the time to look into this issue.

**Comment by kzu** [comment]
I don't quite understand the scenario. The `GeneratePackageOnBuild` should have no effect whatesoever if you're invoking `dotnet pack`, unless I'm missing something :/. So how come removing it made things work with `dotnet pack`?

**Comment by kzu** [comment]
Also, what if you add a `DependsOnTargets="ResolvePackageAssets"` to the target in the article?

**Comment by kzu** [comment]
Found the fix! Adding `DependsOnTargets="ResolvePackageAssets" BeforeTargets="GenerateNuspec"` fixed `dotnet pack` :)

Fixed in https://github.com/kzu/til/commit/8e7a14c7c2c35e6da2303c68aab4d8526a2edf34. Published.

Thanks for helping me improve the content!
